/// static params used in pt. Recomplied is required when changing these params
/// the left values are params used in shader, the right values are macro defined by renderpass


static const bool kUsedReSTIRDI = USE_RESTIRDI;
static const bool kUsedNEE = USE_NEE;
static const bool kUsedMis = USE_MIS;
static const uint kMaxBounces = MAX_GI_BOUNCE;
static const uint kSamplePerPixel = SAMPLE_PER_PIXEL;

static const uint kUsedThp = USE_Thp;
